## Задание по библиотеке NumPy

In [63]:
import numpy as np

print(np.__version__)

1.26.4


Заполнение матрицы M:

In [64]:
size = 85

M = 2 * np.ones((size, size), dtype=int)
np.fill_diagonal(M, 2 * np.arange(size) + 3)
print('M =\n', M)

M =
 [[  3   2   2 ...   2   2   2]
 [  2   5   2 ...   2   2   2]
 [  2   2   7 ...   2   2   2]
 ...
 [  2   2   2 ... 167   2   2]
 [  2   2   2 ...   2 169   2]
 [  2   2   2 ...   2   2 171]]


Заполнение матрицы N:

In [65]:
N = np.zeros((size, size), dtype=int)

# Четные строки
N[::2, :] = 4
N[::2, 2::3] = 5

# Нечетные строки
N[1::2, :] = 4
N[1::2, 1::2] = 7

print('N =\n', N)

N =
 [[4 4 5 ... 4 5 4]
 [4 7 4 ... 4 7 4]
 [4 4 5 ... 4 5 4]
 ...
 [4 4 5 ... 4 5 4]
 [4 7 4 ... 4 7 4]
 [4 4 5 ... 4 5 4]]


Вычисление вектора p:

In [66]:
p = 1 + np.random.normal(loc=2, scale=2, size=size) # (среднее значение, стандартное отклонение, размер матрицы)
print('p =', p)

p = [ 1.11930585e+00  4.05362453e+00  3.27507139e+00  4.29924127e+00
  1.52974139e+00  4.59527446e+00  5.86250891e+00  2.48013258e+00
  4.94398562e+00  4.92481728e-01  4.23105890e+00  6.34616751e+00
  3.64744452e+00  3.68776473e+00  6.63619965e+00  1.32268304e+00
  7.48487709e+00  3.48327587e+00  2.12203350e+00  8.30590115e-01
  2.42026380e+00  1.47576751e+00  4.49406436e+00  7.11053275e-01
  1.22229920e+00  4.19360289e+00  4.96671901e+00  3.34964637e+00
  3.07410748e+00  1.23294045e+00  2.98226947e+00  3.20055422e+00
  2.64064099e+00  1.66560855e+00  4.64371033e+00  3.42949764e+00
  1.95891009e+00  4.02623933e+00  2.75965604e+00  7.62601457e+00
  5.84360843e+00  2.36938893e+00  3.22037822e+00  4.44974511e+00
  1.18373307e+00  4.64164381e+00  3.25588133e+00  1.13311211e+00
  1.25164207e+00  3.48725579e+00  3.39307063e+00  3.58040509e+00
  4.89614765e+00 -2.20269389e+00  6.89094676e+00  5.52606998e-03
  3.04820846e+00  5.23438742e+00  4.95337302e+00  1.81228490e+00
  2.49364480e+00  2.5

Вычисление вектора q:

In [67]:
qT = np.multiply(N[24, :size], N[71, :size])
q = qT.T
print('q =', q)

q = [16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35
 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35
 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35 16 28 20 28 16 35
 16 28 20 28 16 35 16 28 20 28 16 35 16]


Вычисление вектора f:

In [68]:
qqT = np.outer(q, qT)
det_qqT = np.linalg.det(qqT)
f = det_qqT * p
f = det_qqT
print('f =', f)

f = 0.0


Вычисление вектора g:

In [69]:
Mii = np.diag(M)
Nii = np.diag(N)
qTq = np.multiply(qT, q)
difference = Mii - Nii
result = difference + qTq
g = np.linalg.norm(result, ord=2)
print('g =', g)

g = 7181.611727182138
