In [4]:
import numpy as np

print(np.__version__)

1.26.4


In [5]:
size = 85

# Заполнение матрицы M
M = 2 * np.ones((size, size), dtype=int)
np.fill_diagonal(M, 2 * np.arange(size) + 3)

# Заполнение матрицы N
N = np.zeros((size, size), dtype=int)

# Четные строки
N[::2, :] = 4
N[::2, 2::3] = 5

# Нечетные строки
N[1::2, :] = 4
N[1::2, 1::2] = 7

p = 1 + np.random.normal(loc=2, scale=2, size=size) # (среднее значение, стандартное отклонение, размер матрицы)

q = np.multiply(N[24, :size], N[71, :size]) # Поэлементное умножение

print('M =\n', M)
print('N =\n', N)
print('p =', p)
print('q =', q)

M =
 [[  3   2   2 ...   2   2   2]
 [  2   5   2 ...   2   2   2]
 [  2   2   7 ...   2   2   2]
 ...
 [  2   2   2 ... 167   2   2]
 [  2   2   2 ...   2 169   2]
 [  2   2   2 ...   2   2 171]]
N =
 [[4 4 5 ... 4 5 4]
 [4 7 4 ... 4 7 4]
 [4 4 5 ... 4 5 4]
 ...
 [4 4 5 ... 4 5 4]
 [4 7 4 ... 4 7 4]
 [4 4 5 ... 4 5 4]]
p = [ 2.58949626  3.33302936  5.25337195  4.97343399  3.03657012  3.7481582
  3.75339148  6.61694175  1.15803101  3.77387329  3.40126127 -0.79243139
  2.45050698  4.09528742  5.11371449  4.29118049  1.47761453  1.62171714
 -0.21132417  4.45837066  1.97753889  4.76969203  8.17926209  1.01616557
  3.22260766  7.34007288  3.16981955  4.34382666  2.67160765  2.01139783
  1.04816524  4.86685224  5.24200355  4.68014863  2.41741479  4.08863523
  4.18403925 -0.06551621  4.99491094  2.65545291  6.02146612  2.30100413
  2.97749608  5.39429204  1.1324495   2.01490112  6.00557258  2.09391281
  5.94543577  2.26771006  4.34229027  3.46554268  3.970527    3.00968383
 -0.04103163  3.02

In [6]:
f = np.linalg.det(np.outer(q, q**2).T) # Определитель транспонированной матрицы внешнего произведения q и q^2

g_vector = np.diagonal(M) - np.diagonal(N) + (q**2) * q # Поэлементная сумма разности диагоналей и вектора q^3
g = np.linalg.norm(g_vector, ord=2) # L2 норма

print('f =', f)
print('g =', g)

f = 0.0
g = 202105.29393115858
